clear; clc; close all;

%% 
EXCEL_PATH = 'D:\桌面\NO8ctd.xlsx';

TY_START   = datetime(2024,11,9);
TY_END     = datetime(2024,11,11);

X_START    = datetime(2024,11,6);
X_END      = datetime(2024,11,21);

DEPTH_MAX  = 900;

GRID_NT    = 500;
GRID_ND    = 250;

SURF_DEP   = 10;

%% 
FONT_NAME   = 'Arial';

FS_AXIS     = 10;
FS_LABEL    = 11;
FS_LEGEND   = 8;

LW_MAIN     = 2.0;
LW_CONTOUR  = 0.8;
AX_LINE_W   = 1.2;

COL_TICK    = [0 0 0];

COL_BEFORE  = [0.10 0.50 0.90];
COL_DURING  = [1.00 0.20 0.10];
COL_AFTER   = [0.10 0.70 0.20];

COL_SST     = [1.00 0.40 0.00];
COL_SSS     = [0.00 0.60 1.00];

%% 

opts = detectImportOptions(EXCEL_PATH);

opts.VariableNames = {'time','depth','temp','sal'};

T = readtable(EXCEL_PATH, opts);

T.time = datetime(...
    T.time,...
    'InputFormat','yyyy-MM-dd HH:mm:ss');

T = sortrows(T,'time');

fprintf('Loaded %d rows.\n',height(T));

%%
T.c = 1448.96 ...
    + 4.591*T.temp ...
    - 0.304*T.temp.^2 ...
    + 0.015*T.temp.^3 ...
    + 1.34*(T.sal-35) ...
    + 0.016*T.depth;

%% 
t_num = datenum(T.time);

t_grid = linspace(min(t_num),max(t_num),GRID_NT);
d_grid = linspace(0,DEPTH_MAX,GRID_ND);

[TT,DD] = meshgrid(t_grid,d_grid);

TEMP_grid = griddata(...
    t_num,T.depth,T.temp,...
    TT,DD,'linear');

SAL_grid = griddata(...
    t_num,T.depth,T.sal,...
    TT,DD,'linear');

C_grid = griddata(...
    t_num,T.depth,T.c,...
    TT,DD,'linear');

%%
mask_b = T.time < TY_START;

T_before = T(mask_b,:);

bin_size = 25;

T_before.dbin = ...
    floor(T_before.depth/bin_size)*bin_size + bin_size/2;

ubins = unique(T_before.dbin);

c_mean_before = zeros(size(ubins));

for i = 1:length(ubins)

    idx = T_before.dbin == ubins(i);

    c_mean_before(i) = ...
        mean(T_before.c(idx),'omitnan');

end

c_mean_grid = repmat(...
    interp1(...
    ubins,...
    c_mean_before,...
    d_grid,...
    'linear',...
    'extrap')',...
    1,GRID_NT);

C_ANOM_grid = C_grid - c_mean_grid;

%% 
mask_d = T.time >= TY_START & T.time <= TY_END;
mask_a = T.time > TY_END;

T.dbin = ...
    floor(T.depth/bin_size)*bin_size + bin_size/2;

ubins = unique(T.dbin);

prof_temp_b = NaN(size(ubins));
prof_sal_b  = NaN(size(ubins));

prof_temp_d = NaN(size(ubins));
prof_sal_d  = NaN(size(ubins));

prof_temp_a = NaN(size(ubins));
prof_sal_a  = NaN(size(ubins));

for i = 1:length(ubins)

    b = T.dbin == ubins(i);

    prof_temp_b(i) = mean(...
        T.temp(b & mask_b),'omitnan');

    prof_sal_b(i) = mean(...
        T.sal(b & mask_b),'omitnan');

    prof_temp_d(i) = mean(...
        T.temp(b & mask_d),'omitnan');

    prof_sal_d(i) = mean(...
        T.sal(b & mask_d),'omitnan');

    prof_temp_a(i) = mean(...
        T.temp(b & mask_a),'omitnan');

    prof_sal_a(i) = mean(...
        T.sal(b & mask_a),'omitnan');

end

%%
T_surf = T(T.depth <= SURF_DEP,:);

T_surf = sortrows(T_surf,'time');

out_sst = isoutlier(...
    T_surf.temp,...
    'movmedian',5,...
    'ThresholdFactor',3);

out_sss = isoutlier(...
    T_surf.sal,...
    'movmedian',5,...
    'ThresholdFactor',3);

T_surf.temp(out_sst) = NaN;
T_surf.sal(out_sss)  = NaN;

valid_surf = ...
    ~isnan(T_surf.temp) & ...
    ~isnan(T_surf.sal);

T_surf = T_surf(valid_surf,:);

base_sst = mean(...
    T_surf.temp(T_surf.time < TY_START),...
    'omitnan');

base_sss = mean(...
    T_surf.sal(T_surf.time < TY_START),...
    'omitnan');

raw_sst_anom = T_surf.temp - base_sst;
raw_sss_anom = T_surf.sal  - base_sss;

surf_day = dateshift(...
    T_surf.time,...
    'start','day');

[G,day_list] = findgroups(surf_day);

day_temp = splitapply(...
    @(x)mean(x,'omitnan'),...
    T_surf.temp,G);

day_sal = splitapply(...
    @(x)mean(x,'omitnan'),...
    T_surf.sal,G);

day_stdT = splitapply(...
    @(x)std(x,0,'omitnan'),...
    T_surf.temp,G);

day_stdS = splitapply(...
    @(x)std(x,0,'omitnan'),...
    T_surf.sal,G);

sst_anom = day_temp - base_sst;
sss_anom = day_sal  - base_sss;

%% 
fig = figure(...
    'Color',[1 1 1],...
    'Units','centimeters',...
    'Position',[2 2 48 38]);

tl = tiledlayout(3,2,...
    'TileSpacing','compact',...
    'Padding','tight');

x0_num = datenum(X_START);
x1_num = datenum(X_END);

%%
ax1 = nexttile(tl,1);

hold(ax1,'on');

contourf(...
    ax1,...
    t_grid,...
    d_grid,...
    TEMP_grid,...
    80,...
    'LineColor','none');

colormap(ax1,parula);

clim(ax1,[5 28]);

[Ct,ht] = contour(...
    ax1,...
    t_grid,...
    d_grid,...
    TEMP_grid,...
    8:4:28,...
    'LineColor','w',...
    'LineWidth',LW_CONTOUR);

clabel(Ct,ht,...
    'Color',[0.15 0.15 0.15],...
    'FontSize',8,...
    'FontWeight','bold');

c1 = colorbar(ax1);

c1.Label.String = 'Temperature (°C)';
c1.FontName = FONT_NAME;
c1.FontSize = FS_AXIS;

ax1.YDir = 'reverse';
ax1.YLim = [0 900];
ax1.YTick = 0:150:900;

xlim(ax1,[x0_num x1_num]);

datetick(ax1,'x','mm/dd','keepticks');

box(ax1,'on');

ax1.LineWidth = AX_LINE_W;
ax1.FontName  = FONT_NAME;
ax1.FontSize  = FS_AXIS;

ylabel(ax1,'Depth (m)','FontSize',FS_LABEL);
xlabel(ax1,'Date','FontSize',FS_LABEL);

%% 
ax2 = nexttile(tl,2);

hold(ax2,'on');

plot(ax2,prof_temp_b,ubins,...
    '-','Color',COL_BEFORE,...
    'LineWidth',LW_MAIN);

plot(ax2,prof_temp_d,ubins,...
    '-','Color',COL_DURING,...
    'LineWidth',LW_MAIN);

plot(ax2,prof_temp_a,ubins,...
    '-','Color',COL_AFTER,...
    'LineWidth',LW_MAIN);

ax2.YDir = 'reverse';

ax2.YLim = [0 900];
ax2.YTick = 0:100:900;

ax2.XLim = [4.5 29.5];

xlabel(ax2,'Temperature (°C)',...
    'FontSize',FS_LABEL);

ylabel(ax2,'Depth (m)',...
    'FontSize',FS_LABEL);

box(ax2,'on');

ax2.LineWidth = AX_LINE_W;
ax2.FontName  = FONT_NAME;
ax2.FontSize  = FS_AXIS;

%%
drawnow;

pos = ax2.Position;

ax2b = axes(...
    'Parent',fig,...
    'Position',pos,...
    'Color','none',...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'YColor','none',...
    'XColor',COL_TICK,...
    'Box','off',...
    'XLim',[35.0 36.35],...
    'XTick',35.0:0.2:36.4,...
    'YLim',ax2.YLim,...
    'YDir',ax2.YDir,...
    'FontName',FONT_NAME,...
    'FontSize',FS_AXIS,...
    'LineWidth',AX_LINE_W);

hold(ax2b,'on');

plot(ax2b,prof_sal_b,ubins,...
    '--','Color',COL_BEFORE,...
    'LineWidth',1.6);

plot(ax2b,prof_sal_d,ubins,...
    '--','Color',COL_DURING,...
    'LineWidth',1.6);

plot(ax2b,prof_sal_a,ubins,...
    '--','Color',COL_AFTER,...
    'LineWidth',1.6);

xlabel(ax2b,'Salinity (PSU)',...
    'FontSize',FS_AXIS);

linkaxes([ax2 ax2b],'y');

%% 
hLeg = gobjects(6,1);

hLeg(1) = plot(ax2,nan,nan,...
    '-','Color',COL_BEFORE,...
    'LineWidth',LW_MAIN);

hLeg(2) = plot(ax2,nan,nan,...
    '--','Color',COL_BEFORE,...
    'LineWidth',1.6);

hLeg(3) = plot(ax2,nan,nan,...
    '-','Color',COL_DURING,...
    'LineWidth',LW_MAIN);

hLeg(4) = plot(ax2,nan,nan,...
    '--','Color',COL_DURING,...
    'LineWidth',1.6);

hLeg(5) = plot(ax2,nan,nan,...
    '-','Color',COL_AFTER,...
    'LineWidth',LW_MAIN);

hLeg(6) = plot(ax2,nan,nan,...
    '--','Color',COL_AFTER,...
    'LineWidth',1.6);

lgd = legend(...
    ax2,...
    hLeg,...
    {'Before T','Before S',...
     'During T','During S',...
     'After T','After S'},...
    'Location','southeast');

lgd.FontSize = FS_LEGEND;

%% 
ax3 = nexttile(tl,3);

hold(ax3,'on');

contourf(...
    ax3,...
    t_grid,...
    d_grid,...
    SAL_grid,...
    80,...
    'LineColor','none');

colormap(ax3,cool);

clim(ax3,[35.05 36.30]);

[Cs,hs] = contour(...
    ax3,...
    t_grid,...
    d_grid,...
    SAL_grid,...
    35.0:0.3:36.3,...
    'LineColor','w',...
    'LineWidth',LW_CONTOUR);

clabel(Cs,hs,...
    'Color',[0.15 0.15 0.15],...
    'FontSize',8,...
    'FontWeight','bold');

c3 = colorbar(ax3);

c3.Label.String = 'Salinity (PSU)';
c3.FontName = FONT_NAME;
c3.FontSize = FS_AXIS;

ax3.YDir = 'reverse';
ax3.YLim = [0 900];
ax3.YTick = 0:150:900;

xlim(ax3,[x0_num x1_num]);

datetick(ax3,'x','mm/dd','keepticks');

box(ax3,'on');

ax3.LineWidth = AX_LINE_W;
ax3.FontName  = FONT_NAME;
ax3.FontSize  = FS_AXIS;

ylabel(ax3,'Depth (m)','FontSize',FS_LABEL);
xlabel(ax3,'Date','FontSize',FS_LABEL);

%%

hold(ax4,'on');

yyaxis(ax4,'left');

scatter(...
    ax4,...
    T_surf.time,...
    raw_sst_anom,...
    18,...
    'filled',...
    'MarkerFaceColor',COL_SST,...
    'MarkerFaceAlpha',0.18);

h1 = errorbar(...
    ax4,...
    day_list,...
    sst_anom,...
    day_stdT,...
    '-o',...
    'Color',COL_SST,...
    'LineWidth',LW_MAIN,...
    'MarkerFaceColor',COL_SST,...
    'CapSize',0);

ylabel(ax4,...
    'SST anomaly (°C)',...
    'Color',COL_SST,...
    'FontSize',FS_LABEL);

yyaxis(ax4,'right');

scatter(...
    ax4,...
    T_surf.time,...
    raw_sss_anom,...
    18,...
    'filled',...
    'MarkerFaceColor',COL_SSS,...
    'MarkerFaceAlpha',0.18);

h2 = errorbar(...
    ax4,...
    day_list,...
    sss_anom,...
    day_stdS,...
    '-s',...
    'Color',COL_SSS,...
    'LineWidth',LW_MAIN,...
    'MarkerFaceColor',COL_SSS,...
    'CapSize',0);

ylabel(ax4,...
    'SSS anomaly (PSU)',...
    'Color',COL_SSS,...
    'FontSize',FS_LABEL);

xlim(ax4,...
    [datetime(2024,11,5) datetime(2024,11,21)]);

datetick(ax4,'x','mm/dd','keepticks');

box(ax4,'on');

ax4.LineWidth = AX_LINE_W;
ax4.FontName  = FONT_NAME;
ax4.FontSize  = FS_AXIS;

xlabel(ax4,'Date','FontSize',FS_LABEL);

legend(ax4,[h1 h2],...
    {'SST anomaly','SSS anomaly'},...
    'Location','southwest');

%%
ax6 = nexttile(tl,4,[2 1]);

hold(ax6,'on');

contourf(...
    ax6,...
    t_grid,...
    d_grid,...
    C_ANOM_grid,...
    80,...
    'LineColor','none');

colormap(ax6,jet);

clim(ax6,[-4 4]);

[Cc,hc] = contour(...
    ax6,...
    t_grid,...
    d_grid,...
    C_ANOM_grid,...
    -4:2:4,...
    'LineColor','w',...
    'LineWidth',0.9);

clabel(Cc,hc,...
    'Color',[0.15 0.15 0.15],...
    'FontSize',8,...
    'FontWeight','bold');

c6 = colorbar(ax6);

c6.Label.String = '\DeltaC (m/s)';
c6.FontName = FONT_NAME;
c6.FontSize = FS_AXIS;

ax6.YDir = 'reverse';
ax6.YLim = [0 900];
ax6.YTick = 0:150:900;

xlim(ax6,[x0_num x1_num]);

datetick(ax6,'x','mm/dd','keepticks');

box(ax6,'on');

ax6.LineWidth = AX_LINE_W;
ax6.FontName  = FONT_NAME;
ax6.FontSize  = FS_AXIS;

ylabel(ax6,'Depth (m)','FontSize',FS_LABEL);
xlabel(ax6,'Date','FontSize',FS_LABEL);